version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: student_hub_backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Override URL jika mau ngepoint ke Service Backend Docker ini
        VITE_API_URL: http://localhost:8080
        VITE_API_BASE_URL: http://localhost:8080
    container_name: student_hub_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
